name: Some Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Some Input'
        required: false
        default: ''

jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Write Some File
        run: echo "Some Content" > some-file.txt
      - name: Cache File
        uses: actions/cache/save@v3
        with:
          path: some-file.txt
          key: some-file

      - name: Run Action 1
        uses: ./.github/actions/action-1
        with:
          cache-key: some-file

      - name: Run Action 2
        uses: ./.github/actions/action-2